In [10]:
import pandas as pd

In [11]:
#Create a `DataFrame` from a dictionary containing two columns and three rows. Use meaningful custom row labels.

student = pd.DataFrame({
    'Attendence':[100,89,90],
    'Marks':[10,11,12]
},
index=['Student_aaa','Student_bbb','Student_cccc']
)

student

              Attendence  Marks
Student_aaa          100     10
Student_bbb           89     11
Student_cccc          90     12

In [12]:
#Create a `Series` containing three values, assign three custom row labels, and give the `Series` an overall name.
someValues = pd.Series(
    [1,2,3],
    index=['val1','val2','val3'],
    name='values')

someValues

val1    1
val2    2
val3    3
Name: values, dtype: int64

In [4]:
#Given a CSV path, load it into a variable and then inspect its dimensions and first five rows using the techniques from the tutorial.
from pathlib import Path
import pandas as pd

project_root = next(
    folder for folder in (Path.cwd(), *Path.cwd().parents)
    if (folder / ".git").exists()
)

csv_path = (
    project_root
    / "Practice"
    / "Pandas"
    / "DataFiles"
    / "pandas_practice_dataset.csv"
)


df = pd.read_csv(csv_path)

print(f"Head \n",df.head())
print(f"\n Shape\n",df.shape)

Head
    ID     Name   Age       City              Date  Experience  Score  \
0   1  Anudeep  37.0  Bangalore        2025-01-10           8   72.0
1   2     Ravi  32.0    Chennai        15/01/2025           6   65.0
2   3    Priya  29.0  Hyderabad  January 20, 2025           5   78.0
3   4     John  40.0  Bangalore        2025/01/25          10   88.0
4   5    Meena   NaN     Mumbai        02/02/2025           7   70.0

      Salary
0  1200000.0
1   900000.0
2   800000.0
3  1500000.0
4   950000.0

 Shape
 (15, 8)

In [10]:
#Modify a `read_csv()` call so that the first CSV column is used as the `DataFrame` index.
df = pd.read_csv(csv_path,index_col=0)
df

       Name   Age       City               Date  Experience  Score     Salary
ID
1   Anudeep  37.0  Bangalore         2025-01-10           8   72.0  1200000.0
2      Ravi  32.0    Chennai         15/01/2025           6   65.0   900000.0
3     Priya  29.0  Hyderabad   January 20, 2025           5   78.0   800000.0
4      John  40.0  Bangalore         2025/01/25          10   88.0  1500000.0
5     Meena   NaN     Mumbai         02/02/2025           7   70.0   950000.0
6      Arun  35.0      Delhi         2025-02-10           4   60.0        NaN
7     Kiran  31.0    Chennai  February 15, 2025           8    NaN  1100000.0
8      Ravi  32.0    Chennai         15/01/2025           6   65.0   900000.0
9     Divya  27.0  Bangalore         2025-03-05           3   55.0   700000.0
10   Suresh  45.0     Mumbai         10/03/2025          12   92.0  1800000.0
11     Neha  30.0  Hyderabad     March 20, 2025           5   68.0   820000.0
12    Vijay  38.0      Delhi         2025-03-25           9   85.0  1350000.0
13     Asha  28.0  Bangalore         2025/04/02           4   62.0   760000.0
14    Rahul  34.0    Chennai         05/04/2025           7   74.0   980000.0
15    Pooja  26.0     Mumbai     April 10, 2025           2   48.0   650000.0