# List to follow 
1.Loading the data 
2.Inpecting the raw data

In [74]:
import numpy as np
import pandas as pd

df_original = pd.read_csv("Titanic.csv")

## 2.Inpecting the raw data

In [75]:
df_original.shape

(1309, 14)

In [76]:
df_original.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1309 non-null   str
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1309 non-null   str
 9   cabin      1309 non-null   str
 10  embarked   1309 non-null   str
 11  boat       1309 non-null   str
 12  body       1309 non-null   str
 13  home.dest  1309 non-null   str
dtypes: int64(4), str(10)
memory usage: 143.3 KB

In [77]:
df_original.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29,0,0,24160,211.3375,B5,S,2,?,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.55,C22 C26,S,11,?,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30,1,2,113781,151.55,C22 C26,S,?,135,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25,1,2,113781,151.55,C22 C26,S,?,?,"Montreal, PQ / Chesterville, ON"

In [78]:
df_original.describe()

            pclass     survived        sibsp        parch
count  1309.000000  1309.000000  1309.000000  1309.000000
mean      2.294882     0.381971     0.498854     0.385027
std       0.837836     0.486055     1.041658     0.865560
min       1.000000     0.000000     0.000000     0.000000
25%       2.000000     0.000000     0.000000     0.000000
50%       3.000000     0.000000     0.000000     0.000000
75%       3.000000     1.000000     1.000000     0.000000
max       3.000000     1.000000     8.000000     9.000000

In [79]:
df_original.duplicated().sum()

np.int64(0)

In [80]:
df_original.nunique()

pclass          3
survived        2
name         1307
sex             2
age            99
sibsp           7
parch           8
ticket        929
fare          282
cabin         187
embarked        4
boat           28
body          122
home.dest     370
dtype: int64

In [81]:
df_original.sample(10)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
81,1,0,"Crosby, Capt. Edward Gifford",male,70,1,1,WE/P 5735,71,B22,S,?,269,"Milwaukee, WI"
591,2,1,"West, Miss. Constance Mirium",female,5,1,2,C.A. 34651,27.75,?,S,10,?,"Bournmouth, England"
702,3,0,"Canavan, Miss. Mary",female,21,0,0,364846,7.75,?,Q,?,?,?
1134,3,0,"Pokrnic, Mr. Tome",male,24,0,0,315092,8.6625,?,S,?,?,?
1303,3,0,"Yousseff, Mr. Gerious",male,?,0,0,2627,14.4583,?,C,?,?,?
229,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17,1,0,PC 17758,108.9,C65,C,8,?,"Madrid, Spain"
501,2,1,"Mellinger, Miss. Madeleine Violet",female,13,0,1,250644,19.5,?,S,14,?,"England / Bennington, VT"
263,1,1,"Silvey, Mrs. William Baird (Alice Munger)",female,39,1,0,13507,55.9,E44,S,11,?,"Duluth, MN"
684,3,0,"Bourke, Mrs. John (Catherine)",female,32,1,1,364849,15.5,?,Q,?,?,"Ireland Chicago, IL"
622,3,0,"Andersson, Master. Sigvard Harald Elias",male,4,4,2,347082,31.275,?,S,?,?,"Sweden Winnipeg, MN"

In [82]:
df_original['survived'].value_counts()

survived
0    809
1    500
Name: count, dtype: int64

### Data Inspection Observations

### Overview
| Property | Value |
|---|---|
| Rows | 1,309 |
| Columns | 14 |
| Duplicates | 0 |

### Column-level observations
| Column | Dtype | Non-null Count | Suspicious Values | Action Needed |
|---|---|---|---|---|
| pclass | int64 | 1,309 | None | None |
| survived | int64 | 1,309 | None | None |
| name | object | 1,309 | None | None |
| sex | object | 1,309 | None | None |
| age | object | 1,309 | `?` found — should be numeric | Replace `?` with NaN, convert to float |
| sibsp | int64 | 1,309 | None | None |
| parch | int64 | 1,309 | None | None |
| ticket | object | 1,309 | None | None |
| fare | object | 1,309 | `?` found — should be numeric | Replace `?` with NaN, convert to float |
| cabin | object | 1,309 | `?` found | Investigate missingness |
| embarked | object | 1,309 | None visible | Investigate missingness |
| boat | object | 1,309 | Mixed numbers and letters | Labels, not quantities — do not convert to numeric |
| body | object | 1,309 | `?` found — should be numeric | Replace `?` with NaN, convert to float |
| home.dest | object | 1,309 | Many visibly empty cells | Investigate missingness |

### Overall notes
| # | Observation |
|---|---|
| 1 | `info()` reports all 1,309 values as non-null, but `head()` shows `?` in age, fare, and body — `?` is a missing-value placeholder, not a real value |
| 2 | Three columns (age, fare, body) are stored as `object` because of the `?` entries — dtype conversion needed after placeholder replacement |
| 3 | cabin and home.dest appear sparse from `head()` — likely high missingness once `?` is replaced |
| 4 | boat contains mixed alphanumeric labels — category, not a numeric quantity |
| 5 | No duplicate rows found |

## 2.Fixing the placeholder
in this case its "?" it can be anything
keep the original df as it is and create a copy and work on it

In [83]:
df_clean = df_original.copy()

In [84]:
print(f"Cells containing '?' before: {(df_clean == '?').sum().sum()}")
df_clean = df_clean.replace('?',np.nan)
print(f"Cells containing '?' after: {(df_clean == '?').sum().sum()}")

Cells containing '?' before: 3855
Cells containing '?' after: 0

In [85]:
print("=== ORIGINAL ===")
df_original.info()

print("\n=== CLEAN ===")
df_clean.info()

=== ORIGINAL ===
<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1309 non-null   str
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1309 non-null   str
 9   cabin      1309 non-null   str
 10  embarked   1309 non-null   str
 11  boat       1309 non-null   str
 12  body       1309 non-null   str
 13  home.dest  1309 non-null   str
dtypes: int64(4), str(10)
memory usage: 143.3 KB

=== CLEAN ===
<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1046 non-null   str
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1308 non-null   str
 9   cabin      295 non-null    str
 10  embarked   1307 non-null   str
 11  boat       486 non-null    str
 12  body       121 non-null    str
 13  home.dest  745 non-null    str
dtypes: int64(4), str(10)
memory usage: 143.3 KB

In [86]:
# Shows non-null count for both side by side
#df.count() counts the non-null values per column — it excludes NaN but counts everything else, including ?.
pd.DataFrame({
    'original': df_original.count(),
    'clean': df_clean.count()
})

           original  clean
pclass         1309   1309
survived       1309   1309
name           1309   1309
sex            1309   1309
age            1309   1046
sibsp          1309   1309
parch          1309   1309
ticket         1309   1309
fare           1309   1308
cabin          1309    295
embarked       1309   1307
boat           1309    486
body           1309    121
home.dest      1309    745

# dtype conversion
 identified age,fare and body as object/string it should be number.

In [87]:
'''
It converts to float64 by default when the column contains NaN, and int64 when there are no NaNs.

In your case all three columns (age, fare, body) have NaNs from the ? replacement, so they will all become float64.

The reason is what concept 2 mentions: standard integers cannot hold NaN in pandas. So any numeric column with missing values automatically becomes float64. That’s expected, not an error.
'''

numeric_columns = ['age','fare','body']

for column in numeric_columns:
    df_clean[column] = pd.to_numeric(df_clean[column], errors='coerce')  #Without errors='coerce', pd.to_numeric() uses errors='raise' by default — it stops and throws an error the moment it hits a value it can’t convert.


df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    str
 10  embarked   1307 non-null   str
 11  boat       486 non-null    str
 12  body       121 non-null    float64
 13  home.dest  745 non-null    str
dtypes: float64(3), int64(4), str(7)
memory usage: 143.3 KB

## 5.measuring missingness

In [88]:
missing_count = df_clean.isna().sum().sort_values(ascending=False)
missing_percentage = (missing_count / len(df_clean) * 100).round(2)
missing_summary = pd.DataFrame({
    'missing_count': missing_count,
    'missing_percentage': missing_percentage
})

missing_summary

           missing_count  missing_percentage
body                1188               90.76
cabin               1014               77.46
boat                 823               62.87
home.dest            564               43.09
age                  263               20.09
embarked               2                0.15
fare                   1                0.08
sibsp                  0                0.00
name                   0                0.00
survived               0                0.00
pclass                 0                0.00
sex                    0                0.00
parch                  0                0.00
ticket                 0                0.00

In [89]:
#Only show columns that actually have missing values

'''
Breaking it down:

missing_summary['missing_count']

Selects the missing_count column from the summary table
Gives you a Series of numbers like 1188, 1014, 263, 0, 0...

> 0

Compares each number against 0
Returns True where count is greater than 0, False where it’s 0

missing_summary[...]

Uses that True/False result to filter the rows
Only rows where True are kept — meaning only columns that have at least one missing value
'''
missing_summary[missing_summary['missing_count'] > 0]

           missing_count  missing_percentage
body                1188               90.76
cabin               1014               77.46
boat                 823               62.87
home.dest            564               43.09
age                  263               20.09
embarked               2                0.15
fare                   1                0.08

In [90]:
#Check rows with missing values
df_clean.isnull().any(axis=1).sum()

np.int64(1309)

## Measuring Missingness

### What each line does

**Line 1 — Count missing values per column**
```python
missing_count = df_clean.isna().sum().sort_values(ascending=False)
```
- `df_clean.isna()` — marks every cell `True` if missing, `False` if not   [df_clean.isna().sum() gives you one number per column: the total missing values in that]
- `.sum()` — counts the `True` values per column (True=1, False=0)
- `.sort_values(ascending=False)` — sorts columns from most missing to least
- Result: a Series with missing count per column, worst first

**Line 2 — Convert counts to percentages**
```python
missing_percentage = (missing_count / len(df_clean) * 100).round(2)
```
- `missing_count / len(df_clean)` — divides each count by total rows (1,309)
- `* 100` — converts to percentage
- `.round(2)` — keeps 2 decimal places
- Result: same Series but as percentages

**Line 3 — Build the summary table**
```python
missing_summary = pd.DataFrame({
    'missing_count': missing_count,
    'missing_percentage': missing_percentage
})
```
- `pd.DataFrame({...})` — builds a table from both Series
- The keys become column headers
- Both Series share the same index (column names), so each row lines up correctly
- Result: one table, one row per feature

**Line 4 — Display the table**
```python
missing_summary
```
- Just displays the table. No code, just telling Jupyter to render it.

## 6 domain check

### Check 1 — Survival rate of passengers who had a boat:

In [91]:
has_boat = df_clean['boat'].notna()
survival_rate_with_boat = df_clean.loc[has_boat, 'survived'].mean() * 100
survival_rate_without_boat = df_clean.loc[~has_boat, 'survived'].mean() * 100

print(f'Survival rate WITH a boat:    {survival_rate_with_boat:.2f}%')
print(f'Survival rate WITHOUT a boat: {survival_rate_without_boat:.2f}%')

Survival rate WITH a boat:    98.15%
Survival rate WITHOUT a boat: 2.79%

98.15% of passengers who had a boat value survived.

A lifeboat assignment is an almost perfect signal of survival.
Only 9 people who had a boat did not survive — those are suspicious rows worth investigating.

2.79% of passengers without a boat survived.

Almost everyone without a boat died.
The small 2.79% are likely people who survived by other means — pulled from the water, for example.

The domain rule this confirms:
A boat value → almost certainly survived. No boat value → almost certainly did not.

### 2. contradiction check — passengers who had a boat but did not survive

In [92]:
died_with_boat = df_clean[has_boat & (df_clean['survived'] == 0)]

print(f'Passengers with a boat who did not survive: {len(died_with_boat)}')
died_with_boat[['name', 'pclass', 'survived', 'boat']]

Passengers with a boat who did not survive: 9

                                                   name  pclass  survived boat
19                                 Beattie, Mr. Thomson       1         0    A
166                            Hoyt, Mr. William Fisher       1         0   14
544                             Renouf, Mr. Peter Henry       2         0   12
655                          Backstrom, Mr. Karl Alfred       3         0    D
853                  Harmer, Mr. Abraham (David Lishin)       3         0    B
921                                   Keefe, Mr. Arthur       3         0    A
968                       Lindell, Mr. Edvard Bengtsson       3         0    A
969   Lindell, Mrs. Edvard Bengtsson (Elin Gerda Per...       3         0    A
1299                                Yasbeck, Mr. Antoni       3         0    C

A few observations:

The Lindell couple (rows 968, 969) — husband and wife, both on boat A, both marked as not survived. Likely a data entry error — historically, Mrs. Lindell survived but Mr. Lindell did not. The wife’s record is probably wrong.

Boat A appears 4 times — Beattie, Keefe, Lindell ×2 all show boat A. Boat A was a collapsible lifeboat that had a complicated story — some people on it didn’t make it. So this may not be a data error but a real edge case.

What to do with these rows:

They are flagged, not fixed at this stage.
In a real project you’d investigate each one against historical records.
For this exercise, we note them and move on — the domain check has done its job.

### 3.body check:

In [93]:
has_body = df_clean['body'].notna()
survival_rate_with_body = df_clean.loc[has_body, 'survived'].mean() * 100

print(f'Passengers with a body number: {has_body.sum()}')
print(f'Survival rate with a body number: {survival_rate_with_body:.2f}%')

Passengers with a body number: 121
Survival rate with a body number: 0.00%

you don’t even need to run the code to know the answer. If a body number exists, the passenger died and their body was recovered. Survival rate will be 0.00% by definition.

It’s still worth running once just to confirm the data matches the domain rule — that’s the whole point of concept 4. If it showed anything other than 0.00%, that would be a data error worth investigating, just like the 9 boat contradictions. it’s a confirmation check

## 5.dropping features

Based on what we found so far, these columns are being dropped:

|Column	| Reason |
|---|---|
|body	| 91% missing, only describes victims |
|cabin	| 77% missing, too incomplete |
|boat	| Labels not quantities, leaks the target |
|home.dest | 43% missing, not relevant to survival |

In [94]:
df_drop = df_clean.copy()

columns_to_drop = ['body', 'cabin', 'boat', 'home.dest']

#columns_to_drop

df_drop = df_clean.drop(columns=columns_to_drop)

#df_drop 

print('Original columns:', df_clean.shape[1])
print('Working copy columns:', df_drop.shape[1])
df_drop.info()

Original columns: 14
Working copy columns: 10
<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   survived  1309 non-null   int64
 2   name      1309 non-null   str
 3   sex       1309 non-null   str
 4   age       1046 non-null   float64
 5   sibsp     1309 non-null   int64
 6   parch     1309 non-null   int64
 7   ticket    1309 non-null   str
 8   fare      1308 non-null   float64
 9   embarked  1307 non-null   str
dtypes: float64(2), int64(4), str(4)
memory usage: 102.4 KB

## 6. categorical features

## Categorical Features

### Standard checks for each categorical column

| Step | Code | Purpose |
|---|---|---|
| 1. Count unique categories | `df_clean['col'].nunique()` | How many distinct values exist |
| 2. List the categories | `df_clean['col'].unique()` | What those values actually are |
| 3. Frequency of each category | `df_clean['col'].value_counts()` | How common each value is |
| 4. Frequency including missing | `df_clean['col'].value_counts(dropna=False)` | Spots unexpected values and NaN in one call |
| 5. Percentage per category | `df_clean['col'].value_counts(normalize=True) * 100` | Relative size of each category |

> Steps 3 and 4 together are the most useful — run them on every categorical column.

---

### Three questions to ask per column

**1. Are the values valid?**
- No typos, no inconsistent casing, no unexpected categories
- If found → fix in cleaning (e.g. `df_clean['sex'].str.lower()`)

**2. Are there missing values?**
- If yes → fill in imputation stage
- If no → nothing to do

**3. Is the column usable for a model?**
- Categorical text columns need encoding (text → numbers)
- But encoding happens in **preprocessing**, not here

---

### Fix now vs fix later

| Situation | Action | Stage |
|---|---|---|
| Inconsistent labels (`'Male'`, `'male'`, `'MALE'`) | Fix | Cleaning |
| Typos (`'Southhampton'` instead of `'S'`) | Fix | Cleaning |
| Text that needs converting to numbers | Encode | Preprocessing |
| Rare categories to merge | Combine | Preprocessing |
| Dummy variables / one-hot encoding | Create | Preprocessing |

> **Rule: quality problems → fix in cleaning. Form changes → leave for preprocessing.**

---

### Why not encode here?

- Encoding loses the original labels (`male/female` becomes `0/1`) — harder to read and debug
- Preprocessing can be changed without touching cleaning
- Different encoding strategies can be tried without redoing cleaning

---

### Findings — Titanic dataset

| Column | Unique Values | Counts | Missing | Action |
|---|---|---|---|---|
| `sex` | male, female | male=843, female=466 | 0 | None — encode in preprocessing |
| `embarked` | S, C, Q | S=914, C=270, Q=123 | 2 | Fill with mode in imputation |
| `name` | 1,307 unique | — | 0 | Identifier — drop in preprocessing |
| `ticket` | 929 unique | — | 0 | Identifier — drop in preprocessing |

Both `sex` and `embarked` are clean — no typos, no unexpected values.

In [95]:
# Step 1 — Count unique categories
print("Unique count:")
print(df_drop['sex'].nunique())
print(df_drop['embarked'].nunique())
print()

# Step 2 — List the categories
print("Unique values:")
print(df_drop['sex'].unique())
print(df_drop['embarked'].unique())
print()

# Step 3 — Frequency of each category
print("Value counts:")
print(df_drop['sex'].value_counts())
print(df_drop['embarked'].value_counts())
print()

# Step 4 — Frequency including missing
print("Value counts (including NaN):")
print(df_drop['sex'].value_counts(dropna=False))
print(df_drop['embarked'].value_counts(dropna=False))
print()

# Step 5 — Percentage per category
print("Percentage:")
print(df_drop['sex'].value_counts(normalize=True) * 100)
print(df_drop['embarked'].value_counts(normalize=True) * 100)

Unique count:
2
3

Unique values:
<StringArray>
['female', 'male']
Length: 2, dtype: str
<StringArray>
['S', 'C', nan, 'Q']
Length: 4, dtype: str

Value counts:
sex
male      843
female    466
Name: count, dtype: int64
embarked
S    914
C    270
Q    123
Name: count, dtype: int64

Value counts (including NaN):
sex
male      843
female    466
Name: count, dtype: int64
embarked
S      914
C      270
Q      123
NaN      2
Name: count, dtype: int64

Percentage:
sex
male      64.400306
female    35.599694
Name: proportion, dtype: float64
embarked
S    69.931140
C    20.657995
Q     9.410865
Name: proportion, dtype: float64

Then if step 2 or 4 reveals any finding like we have inconsistant casing like 'Male' and 'male', fix it:

In [96]:
# 1. Apply the fix
df_drop['sex'] = df_drop['sex'].str.lower().str.strip()
df_drop['embarked'] = df_drop['embarked'].str.lower().str.strip()

# 2. Verify
print(df_drop['sex'].value_counts(dropna=False))
print()
print(df_drop['embarked'].value_counts(dropna=False))


df_drop[['sex','embarked']]

sex
male      843
female    466
Name: count, dtype: int64

embarked
s      914
c      270
q      123
NaN      2
Name: count, dtype: int64

         sex embarked
0     female        s
1       male        s
2     female        s
3       male        s
4     female        s
...      ...      ...
1304  female        c
1305  female        c
1306    male        c
1307    male        c
1308    male        s

[1309 rows x 2 columns]

## 7. Imputation
Replacing the missing values using a stated rules

In [97]:
# Age — fill with mode
age_mode = df_drop['age'].mode().iloc[0]   # .iloc[0]  - since the mode can return many value i am asking to give me first one 
print(f'Age mode: {age_mode}')
df_drop['age'] = df_drop['age'].fillna(age_mode)

# Embarked — fill with mode
embarked_mode = df_drop['embarked'].mode().iloc[0]
print(f'Embarked mode: {embarked_mode}')
df_drop['embarked'] = df_drop['embarked'].fillna(embarked_mode)

# Fare — fill with mode
fare_mode = df_drop['fare'].mode().iloc[0]
print(f'Fare mode: {fare_mode}')
df_drop['fare'] = df_drop['fare'].fillna(fare_mode)

Age mode: 24.0
Embarked mode: s
Fare mode: 8.05

In [98]:
df_drop.isna().sum()

pclass      0
survived    0
name        0
sex         0
age         0
sibsp       0
parch       0
ticket      0
fare        0
embarked    0
dtype: int64

## Final check 
After cleaning, always verify the data before moving to preprocessing.
Run each check and confirm the expected result.

### 1. Duplicates — did cleaning introduce any?
**Expected:** 0 — cleaning should never introduce duplicate rows.

In [99]:
df_drop.duplicated().sum()

np.int64(0)

### 2. Shape — are the dimensions correct?
**Expected:** 1,309 rows, 10 columns.

In [100]:
print(f'Rows: {df_drop.shape[0]}')
print(f'Columns: {df_drop.shape[1]}')

Rows: 1309
Columns: 10

### 3. Value ranges — did imputation introduce anything odd?
**What to check:**
- `age` min and max still make sense (no negatives, no 999)
- `fare` has no negative values
- `survived` is still only 0 and 1
- `pclass` is still only 1, 2, 3

In [101]:
df_drop.describe()

,pclass,survived,age,sibsp,parch,fare
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000
mean,2.294882,0.381971,28.699516,0.498854,0.385027,33.276193
std,0.837836,0.486055,13.097103,1.041658,0.865560,51.743584
min,1.000000,0.000000,0.166700,0.000000,0.000000,0.000000
25%,2.000000,0.000000,22.000000,0.000000,0.000000,7.895800
50%,3.000000,0.000000,24.000000,0.000000,0.000000,14.454200
75%,3.000000,1.000000,35.000000,1.000000,0.000000,31.275000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200

### 4. Categorical values — are they still consistent?
**Expected:**
- `sex` → only `male`, `female`
- `embarked` → only `s`, `c`, `q`

In [102]:
print(df_drop['sex'].unique())
print(df_drop['embarked'].unique())

<StringArray>
['female', 'male']
Length: 2, dtype: str
<StringArray>
['s', 'c', 'q']
Length: 3, dtype: str


**Expected:** both show 1,309.
Cleaning fixes values — it should never silently drop rows.### 5. Row count — same as original?

In [103]:
print(f'Original: {df_original.shape[0]} rows')
print(f'Cleaned:  {df_drop.shape[0]} rows')

Original: 1309 rows
Cleaned:  1309 rows

### 6. Visual check — does the data look right?
**What to check:**
- No obvious junk values visible
- Column names are correct
- Values look sensible

In [ ]:
df_drop.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,s
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,s
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,s
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,s
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,s

:

### What a passing final check confirms

| Check | What it rules out |
|---|---|
| No duplicates | Cleaning didn't merge or repeat rows |
| Correct shape | No accidental row or column drops |
| Sensible ranges | Imputation didn't introduce outliers |
| Consistent categories | Standardisation didn't corrupt values |
| Same row count as original | No silent data loss |
| Clean head() | No obvious remaining issues |

---

> **Cleaning ends here.** The data is now consistent and complete.
> The next stage is **preprocessing** — encoding categories into numbers
> and scaling numeric features so a model can use them.